eureka:
  client:
    service-url:
      defaultZone: http://${holiday-eureka-host:localhost}:8761/eureka

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: rabbit
  rabbitmq:
    host: localhost